Repository JetBrains/resharper-unity, pull requests merged in 2018-11, with the labels that each got.

#883 Minor build updates
  resharper/.idea/.idea.resharper-unity/.idea/runConfigurations/runIde__offline_.xml
  resharper/gradle-launcher/Program.cs
  rider/model.gradle
Labels: refactor

#873 Find method usage in YAML files
  resharper/resharper-unity/src/CSharp/Daemon/Stages/GutterMarks/UnityEventHandlerDetector.cs
  resharper/resharper-unity/src/CSharp/Daemon/UsageChecking/UsageInspectionsSuppressor.cs
  resharper/resharper-unity/src/Cg/Daemon/Stages/CgDaemonStageBase.cs
  resharper/resharper-unity/src/Rider/UnityOptionsPage.cs
  resharper/resharper-unity/src/Settings/UnitySettings.cs
  resharper/resharper-unity/src/Yaml/ProjectModel/UnityYamlFileExtensionMapping.cs
  resharper/resharper-unity/src/Yaml/Psi/Caches/MetaFileCacheItem.cs
  resharper/resharper-unity/src/Yaml/Psi/Caches/MetaFileGuidCache.cs
  resharper/resharper-unity/src/Yaml/Psi/Caches/UnityEventHandlerReferenceCache.cs
  resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFileProperties.cs
  resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesModuleFactory.cs
  resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesModuleProcessor.cs
  resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesPsiModule.cs
  resharper/resharper-unity/src/Yaml/Psi/Modules/UnityMiscFilesProjectPsiModuleProvider.cs
  resharper/resharper-unity/src/Yaml/Psi/Modules/UnityYamlAssetPsiSourceFile.cs
  resharper/resharper-unity/src/Yaml/Psi/Modules/UnityYamlExternalPsiSourceFile.cs
  resharper/resharper-unity/src/Yaml/Psi/Modules/UnityYamlPsiSourceFileFactory.cs
  resharper/resharper-unity/src/Yaml/Psi/Resolve/UnityEventTargetReference.cs
  resharper/resharper-unity/src/Yaml/Psi/Resolve/UnityEventTargetReferenceFactory.cs
  resharper/resharper-unity/src/Yaml/Psi/Resolve/UnityEventTargetReferenceProviderFactory.cs
  resharper/resharper-unity/src/Yaml/UnityYamlFileExtensions.cs
  resharper/resharper-unity/test/src/CSharp/Daemon/Stages/Analysis/CSharpHighlightingTestBase.cs
  resharper/resharper-yaml/src/Daemon/Stages/Resolve/ResolveProblemHighlighter.cs
  resharper/resharper-yaml/src/Daemon/Stages/YamlDaemonStageBase.cs
  resharper/resharper-yaml/src/ProjectModel/YamlProjectFileType.cs
  resharper/resharper-yaml/src/Psi/Parsing/YamlLexerGenerated.cs
  resharper/resharper-yaml/src/Psi/Parsing/YamlTokenType.CommentNodeType.cs
  resharper/resharper-yaml/src/Psi/Parsing/YamlTokenType.FixedTokenNodeType.cs
  resharper/resharper-yaml/src/Psi/Parsing/YamlTokenType.GenericTokenNodeType.cs
  resharper/resharper-yaml/src/Psi/Parsing/YamlTreeStructureBuilder.cs
  resharper/resharper-yaml/src/Psi/PsiExtensions.cs
  resharper/resharper-yaml/src/Psi/Search/YamlReferenceSearcher.cs
  resharper/resharper-yaml/src/Psi/Search/YamlUsageSearchFactory.cs
  resharper/resharper-yaml/src/Psi/YamlProjectFileLanguageService.cs
  resharper/resharper-yaml/src/Settings/YamlSettings.cs
  resharper/resharper-yaml/src/Settings/YamlSupport.cs
  resharper/resharper-yaml/test/data/Psi/Parsing/Unity/FolderMeta.meta
  resharper/resharper-yaml/test/data/Psi/Parsing/Unity/FolderMeta.meta.gold
  resharper/resharper-yaml/test/data/Psi/Parsing/Unity/Gems-InvalidStripped.unity
  resharper/resharper-yaml/test/data/Psi/Parsing/Unity/Gems-InvalidStripped.unity.gold
  resharper/resharper-yaml/test/data/Psi/Parsing/Unity/PluginMeta.meta
  resharper/resharper-yaml/test/data/Psi/Parsing/Unity/PluginMeta.meta.gold
  resharper/resharper-yaml/test/data/Psi/Parsing/Unity/SpaceShooter.unity
  resharper/resharper-yaml/test/data/Psi/Parsing/Unity/SpaceShooter.unity.gold
  resharper/resharper-yaml/test/data/Psi/Parsing/Unity/StrippedExample.unity
  resharper/resharper-yaml/test/data/Psi/Parsing/Unity/StrippedExample.unity.gold
  resharper/resharper-yaml/test/src/ProjectModel/YamlProjectFileTypeTests.cs
  resharper/resharper-yaml/test/src/Psi/Parsing/UnityParserTests.cs
  resharper/resharper-yaml/test/src/RiderTestsSpecificYamlFileExtensionMapping.cs
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/yaml/UnityYamlFileType.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/yaml/UnityYamlFileTypeFactory.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/yaml/UnityYamlIconProvider.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/yaml/UnityYamlLanguage.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/yaml/UnityYamlParserDefinition.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityIcons.kt
  rider/src/main/resources/META-INF/plugin.xml
Labels: yaml

#891 Minor updates to icons and YAML file types
  resharper/resharper-unity/src/Json/Feature/ReSpeller/Analyzers/UnityByExtensionFileFilter.cs
  resharper/resharper-yaml/src/Psi/YamlProjectFileLanguageService.cs
  resharper/resharper-yaml/test/src/Psi/Parsing/LexerTests.cs
  resharper/resharper-yaml/test/src/UnityTestsSpecificYamlFileExtensionMapping.cs
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/actions/UnityPluginShowSettingsAction.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorer.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/yaml/UnityYamlFileType.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/yaml/UnityYamlFileTypeFactory.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/yaml/UnityYamlIconProvider.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/UnityToolWindowFactory.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityIcons.kt
  rider/src/main/resources/Icons/common/unityDefault.svg
  rider/src/main/resources/Icons/common/unityDefault_dark.svg
Labels: refactor

#894 Move rdgen config out of source and into gradle
  rider/model.gradle
  rider/protocol/src/main/kotlin/model/editorPlugin/EditorPluginModel.kt
Labels: refactor

#895 Add JS zone requirement to asmdef namespace
  resharper/resharper-unity/src/Json/ZoneMarker.cs
Labels: refactor

#825 [WIP] PlayMode tests
  resharper/resharper-unity.sln.DotSettings
  resharper/resharper-unity/src/Rider/ConnectionTracker.cs
  resharper/resharper-unity/src/Rider/UnitTesting/RunViaUnityEditorStrategy.cs
  resharper/resharper-unity/src/Rider/UnitTesting/UnityNUnitServiceProvider.cs
  resharper/resharper-unity/src/Rider/UnityEditorProtocol.cs
  resharper/resharper-unity/src/Rider/UnityPluginDetector.cs
  resharper/resharper-unity/src/Rider/UnityPluginInstaller.cs
  resharper/resharper-unity/src/Rider/UnityRefreshTracker.cs
  rider/protocol/src/main/kotlin/model/editorPlugin/EditorPluginModel.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityUnitTestUIService.kt
  unity/EditorPlugin/EditorPluginFull.csproj
  unity/EditorPlugin/UnitTesting/EntryPoint.cs
  unity/EditorPlugin/UnitTesting/ModelAdviceExtension.cs
  unity/EditorPlugin/UnitTesting/PlayModeSupport.cs
  unity/EditorPlugin/UnitTesting/TestEvent.cs
  unity/EditorPlugin/UnitTesting/TestEventsCollector.cs
  unity/EditorPlugin/UnitTesting/TestEventsSender.cs
  unity/EditorPlugin/UnitTesting/UnityEditorTestLauncher.cs
  unity/EditorPlugin/Utils/RiderScriptableSingleton.cs
  unity/EditorPlugin/Utils/ScriptObjectSingleton.cs
Labels: WIP

#893 Remove readonly flag when converting auto property
  resharper/resharper-unity/src/CSharp/Feature/Services/ContextActions/AutoPropertyToSerializedBackingFieldAction.cs
  resharper/resharper-unity/test/data/CSharp/Intentions/ContextActions/AutoPropertyToSerializedBackingField/Availability01.cs
  resharper/resharper-unity/test/data/CSharp/Intentions/ContextActions/AutoPropertyToSerializedBackingField/Test02.cs
  resharper/resharper-unity/test/data/CSharp/Intentions/ContextActions/AutoPropertyToSerializedBackingField/Test02.cs.gold
  resharper/resharper-unity/test/data/CSharp/Intentions/ContextActions/AutoPropertyToSerializedBackingField/Test03.cs
  resharper/resharper-unity/test/data/CSharp/Intentions/ContextActions/AutoPropertyToSerializedBackingField/Test03.cs.gold
  resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/UseSerializedBackingField/Test01.cs.gold
  resharper/resharper-unity/test/data/CSharp/Intentions/QuickFixes/UseSerializedBackingField/Test02.cs.gold
  resharper/resharper-unity/test/src/CSharp/Intentions/ContextActions/AutoPropertyToSerializedBackingFieldTests.cs
  resharper/resharper-unity/test/src/CSharp/Intentions/QuickFixes/UseSerializedBackingFieldFixTests.cs
Labels: bug

#869 Fix warnings in frontend + enable warnings as errors
  resharper/resharper-unity/src/resharper-unity.csproj
  resharper/resharper-unity/src/rider-unity.csproj
  resharper/resharper-yaml/src/resharper-yaml.csproj
  resharper/resharper-yaml/src/rider-yaml.csproj
  resharper/resharper-yaml/test/src/tests.resharper-yaml.csproj
  resharper/resharper-yaml/test/src/tests.rider-yaml.csproj
  rider/buildSrc/src/main/kotlin/com/jetbrains/rider/plugins/gradle/tasks/MSBuildTask.kt
  rider/frontend.gradle
  rider/gradle.properties
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/SaveAllTracker.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorer.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/explorer/UnityExplorerPackagesViewUpdater.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorSettingsEditor.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/run/configurations/UnityAttachToEditorViewModel.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/UnityToolWindowFactory.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelEventList.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelModel.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/toolWindow/log/UnityLogPanelView.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityImportantActions.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityImportantActionsGroup.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ui/UnityUIManager.kt
  rider/src/main/resources/META-INF/plugin.xml
Labels: refactor

#903 Updates to YAML support
  resharper/resharper-unity.sln.DotSettings
  resharper/resharper-unity/src/CSharp/Daemon/UsageChecking/UsageInspectionsSuppressor.cs
  resharper/resharper-unity/src/CSharp/Feature/Services/Refactorings/Rename/UnityEventTargetAtomicRenameFactory.cs
  resharper/resharper-unity/src/Rider/UnityOptionsPage.cs
  resharper/resharper-unity/src/Yaml/AssetSerializationMode.cs
  resharper/resharper-unity/src/Yaml/Feature/Services/Occurrences/UnityYamlOccurrenceKindProvider.cs
  resharper/resharper-unity/src/Yaml/Feature/Services/Occurrences/UnityYamlSpecificOccurrenceKindIconProvider.cs
  resharper/resharper-unity/src/Yaml/Feature/Services/Occurrences/UnityYamlSpecificOccurrenceKinds.cs
  resharper/resharper-unity/src/Yaml/Psi/Caches/MetaFileCacheItem.cs
  resharper/resharper-unity/src/Yaml/Psi/Caches/MetaFileGuidCache.cs
  resharper/resharper-unity/src/Yaml/Psi/Caches/UnityEventHandlerReferenceCache.cs
  resharper/resharper-unity/src/Yaml/Psi/Modules/UnityExternalFilesModuleProcessor.cs
  resharper/resharper-unity/src/Yaml/Psi/Modules/UnityMiscFilesProjectPsiModuleProvider.cs
  resharper/resharper-unity/src/Yaml/Psi/Resolve/IUnityYamlReference.cs
  resharper/resharper-unity/src/Yaml/Psi/Resolve/MonoScriptReference.cs
  resharper/resharper-unity/src/Yaml/Psi/Resolve/MonoScriptReferenceFactory.cs
  resharper/resharper-unity/src/Yaml/Psi/Resolve/MonoScriptReferenceProviderFactory.cs
  resharper/resharper-unity/src/Yaml/Psi/Resolve/UnityEventTargetReference.cs
  resharper/resharper-unity/src/Yaml/Psi/Resolve/UnityEventTargetReferenceFactory.cs
  resharper/resharper-unity/src/Yaml/Psi/Resolve/UnityEventTargetReferenceProviderFactory.cs
  resharper/resharper-unity/src/Yaml/Psi/Search/UnityYamlGuidUsageSearchFactory.cs
  resharper/resharper-unity/src/Yaml/Psi/UnityObjectPsiUtil.cs
  resharper/resharper-unity/src/Yaml/Psi/UnityYamlPsiExtensions.cs
  resharper/resharper-unity/src/Yaml/Rider/Host/Feature/UnityYamlExtraGroupingRulesProvider.cs
  resharper/resharper-unity/src/Yaml/UnityYamlFileExtensions.cs
  resharper/resharper-unity/src/rider-unity.csproj.DotSettings
  resharper/resharper-unity/test/data/CSharp/Daemon/UsageChecking/MonoBehaviourMethods01.cs
  resharper/resharper-unity/test/data/CSharp/Daemon/UsageChecking/MonoBehaviourMethods01.gold
  resharper/resharper-unity/test/data/CSharp/Daemon/UsageChecking/PotentialEventHandlerMethodsSerializationNotText.cs
  resharper/resharper-unity/test/data/CSharp/Daemon/UsageChecking/PotentialEventHandlerMethodsSerializationNotText.gold
  resharper/resharper-unity/test/data/CSharp/Daemon/UsageChecking/PotentialEventHandlerMethodsYamlDisabled.cs
  resharper/resharper-unity/test/data/CSharp/Daemon/UsageChecking/PotentialEventHandlerMethodsYamlDisabled.gold
  resharper/resharper-unity/test/src/CSharp/Daemon/UsageChecking/UsageInspectionsSuppressorTest.cs
  resharper/resharper-unity/test/src/Yaml/TestableAssetSerializationMode.cs
  resharper/resharper-yaml/src/Psi/PsiExtensions.cs
  resharper/resharper-yaml/src/Psi/Search/YamlUsageSearchFactory.cs
  resharper/resharper-yaml/src/Settings/YamlSettings.cs
  resharper/resharper-yaml/test/src/UnityTestsSpecificYamlFileExtensionMapping.cs
  rider/src/main/resources/META-INF/PluginYamlPluginPart.xml
  rider/src/main/resources/META-INF/plugin.xml
Labels: yaml
