Repository JetBrains/resharper-unity, pull requests merged in 2020-06, with the labels that each got.

#1687 Temporarily disable debugger extension
  resharper/resharper-unity.sln
  resharper/rider-unity.sln
  rider/frontend.gradle
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/ideaInterop/fileTypes/asmdef/AsmDefActionCallPolicy.kt
  rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/notifications/OpenUnityProjectAsFolderNotification.kt
Labels: affects only this wave, debugger, sdk-update

#1694 Restore debugger extension
  debugger/src/EntityComponentDataSource.cs
  debugger/src/GameObjectChildrenRenderer.cs
  debugger/src/GameObjectChildrenSource.cs
  debugger/src/GameObjectComponentsSource.cs
  debugger/src/MetadataTypeEx.cs
  debugger/src/NamedReferenceDecorator.cs
  debugger/src/SceneRootChildrenRenderer.cs
  debugger/src/SceneRootObjectsSource.cs
  debugger/src/SyntheticGroupObjectValueSourceBase.cs
  debugger/src/UnityObjectValueChildrenProvider.cs
  debugger/src/ValueGroupBase.cs
  debugger/src/debugger.csproj
  resharper/resharper-unity.sln
  resharper/rider-unity.sln
  rider/frontend.gradle
Labels: sdk-update

#1697 Treat Unity's compiled assemblies as user code
  CHANGELOG.md
  debugger/src/debugger.csproj
  resharper/resharper-unity/src/Rider/Host/DebuggerOutputAssemblies/UnityDebuggerOutputAssembliesProviderHost.cs
  rider/src/main/resources/META-INF/plugin.xml
Labels: debugger

#1701 Validate gradle-wrapper.jar before running GH workflows
  .github/workflows/ci.yml
Labels: housekeeping

#1685 Integration with gradle-changelog-plugin
  resharper/resharper-unity/src/resharper-unity.resharper.nuspec
  rider/backend.gradle
  rider/build.gradle
  rider/buildSrc/build.gradle.kts
  rider/frontend.gradle
  rider/src/main/resources/META-INF/plugin.xml
Labels: housekeeping

#1707 Check for Unity solution before looking for additional output assemblies
  resharper/resharper-unity/src/Debugger/Host/Rider/UnityDebuggerOutputAssembliesProviderHost.cs
  resharper/resharper-unity/src/Debugger/Host/Rider/ZoneMarker.cs
Labels: affects only this wave
